### PR TITLE
[#30] Do not use the default secret when deploying the api-server

### PR DESCRIPTION
**Pull request by gaohoward**
Added a script to generate random secret
Updated Dockerfile to generate a random secret into .env 
Removed unused commands in Dockerfile
Updated README

### CODE REVIEW

**Review by lavocatt — COMMENTED** [review]
I'm trying out the build and I'm getting a warning, can you get it fixed please?
image

**Comment by gaohoward** [comment]
> I'm trying out the build and I'm getting a warning, can you get it fixed please? image

Sure will fix that. Thanks Thomas!

**Comment by lavocatt** [comment]
Otherwise, I've tested the build and it works great, thanks Howard

**Review by Msarawan — APPROVED** [review]
Good work Howard !!

**Pull request merged**
