### PR TITLE
[NO-ISSUE] Fix typo in openapi.yml description

### PR DESCRIPTION
**Pull request by gemmellr**

### CODE REVIEW

**Review by lavocatt — APPROVED** [review]
Thanks!!

**Comment by lavocatt** [comment]
Can you update the doc with `yarn build-api-doc` please?

**Comment by gemmellr** [comment]
I don't have yarn installed, or the repo checked out. Will leave it for any interested maintainers who do :)

**Comment by lavocatt** [comment]
That's fair enough! I'll take care of it. Thanks nonetheless for bringing that up.

**Comment by lavocatt** [comment]
Just created https://github.com/artemiscloud/activemq-artemis-jolokia-api-server/pull/7 as a result.

**Pull request closed without merging**
